name: Python Morsels

on: [push, pull_request]

jobs:

  pylint:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with pylint
      run: |
        pip install pylint pylint-json2html
        # pylint *.py **/*.py - runs for all py files in current dir and all subdirs
        # --exit-zero treats all errors as warnings.
        # -f msvs - VSCode report format
        echo '""" This is a dummy file """' > __dummy__.py
        mkdir -p dummy
        echo '""" This is a dummy file """' > dummy/__dummy__.py
        # pylint output
        pylint --exit-zero -r y -f msvs -j 0 *.py **/*.py
        # Save report to html format
        mkdir -p reports/pylint
        pylint --exit-zero -r y -j 0 --load-plugins=pylint_json2html --output-format=jsonextended *.py **/*.py > reports/pylint/report.json
        pylint-json2html -f jsonextended -o reports/pylint/report.html reports/pylint/report.json
    - name: Archive pylint coverage results
      uses: actions/upload-artifact@v1
      with:
        name: pylint-coverage-report
        path: reports/pylint/

  flake8:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8 flake8-html
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        mkdir -p reports/flake8
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=79 --statistics --format=html --htmldir=reports/flake8
    - name: Archive flake8 coverage results
      uses: actions/upload-artifact@v1
      with:
        name: flake8-coverage-report
        path: reports/flake8/

  pytest:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, ubuntu-16.04, windows-2016]
        python-version: [3.7, 3.8]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov pytest-html pytest-sugar
        py.test --cov --html=reports/pytest/report.html
    - name: Archive pytest coverage results
      uses: actions/upload-artifact@v1
      with:
        os: ubuntu-latest
        python-version: 3.7
        name: pytest-coverage-report
        path: reports/pytest/
